### ISSUE TITLE
[dotnet-standard-sdk] Readme

### ISSUE THREAD

**Issue by mediumTaj** [atilatosta/dotnet-standard-sdk#3]
Update readme.md to mirror one of the other SDKs. Include separate ReadMe files for each service.

- [x] Main GitHub page
- [x] Conversation
- [ ] Discovery
- [x] Speech to Text
- [x] Text to Speech
- [ ] Visual Recognition
- [x] Language Translator
- [x] Personality Insights
- [x] Tone Analyzer

**Comment by mediumTaj** [comment]
I have stub README.md files in each service and the main github page. Each service now describes each endpoint. We will need to populate each endpoint description with usage examples.

**Comment by mediumTaj** [comment]
Marking this as blocked for now. We still need `service examples` for each service and `documentation` instructions. We also need badges for `Continuous Integration`, `NuGet` and `Code Coverage`.

**Comment by mediumTaj** [comment]
@atilatosta I'm looking at the structure of the readme files for each service. Should these be moved into each service version of the service? Will each service need it's own project? What do you think?

**Comment by degrim** [comment]
@mediumTaj I could argue either way for separating each service into it's own package.  On the one hand, it would be nice for minimizing dependencies to only include the packages for the service that I want to use, but on the other hand if I'm using multiple services it might be more convenient to just have to include a single package.

**Comment by mediumTaj** [comment]
@degrim Hmm would it be unconventional to offer both? A NuGet package for the whole SDK and packages for each service? Is that confusing? Right now in the ReadMe (`gh-3-readMe` branch) I'm pointing to installation instructions per service and have a link pointing to the download link of the latest release in github. Is that enough or do you think we need to alsoi add a NuGet package for the whole sdk? 

@atilatosta ?

**Comment by degrim** [comment]
@mediumTaj I think if you were to create an empty project which simply listed all of the others as a dependency, that would allow you to essentially offer both without any overlap between the two.  As far as conventions go, I'm not really sure if that would be unconventional, I can't think of any other packages that would face a similar issue to compare.

**Comment by atilatosta** [comment]
@mediumTaj I think it is best to keep each service in a separate package. If we only have one project with all the services inside, we will always force the developer to load all the services, even if he wants to use only one.

**Comment by mediumTaj** [comment]
I think it's ok to keep it separate package for now if there is a case for both separate vs entire packages. Looking at Amazon SDK they look like they're doing separate packages but an msi installer for the whole thing? I haven't downloaded the installer.

https://aws.amazon.com/sdk-for-net/

**Comment by mediumTaj** [comment]
I am merging this into develop for now along with all other feature branches.
