### ISSUE TITLE
[conversation] Unit test failing

### ISSUE THREAD

**Issue by mediumTaj** [atilatosta/dotnet-standard-sdk#36]
Investigate

**Comment by maykonsIBM** [comment]
@mediumTaj What branch did this occur? I tested the development branch and everything is fine.

**Comment by mediumTaj** [comment]
On 'develop' branch. Is it working for you?

**Comment by atilatosta** [comment]
@mediumTaj  and @maykonsIBM I did the pull request review and also did the merge with the 'develop' development branch. What do you think of using 'development' to encode? Other ALM activities for example, we can create separate branches. What do you think about this?

**Comment by atilatosta** [comment]
@maykonsIBM  Please make a branch development sync and see if the error remains

**Comment by atilatosta** [comment]
@mediumTaj i saw your e-mail now. I think we can follow your suggestion of branch nomenclature. Let's start now from branch development, what do you think?

**Comment by mediumTaj** [comment]
@atilatosta It doesn't really matter much which non-master branch we are merging to. `develop` is more common here. It is shorter to type than `development`. But if `development` feels better to you I don't mind changing over. I will do a pull request from `develop` to `development` if that sounds right.

**Comment by mediumTaj** [comment]
@atilatosta @maykonsIBM I deleted the `develop` branch and our main dev branch will be `development`. Our trunk is still `master` and we should probably have a `release` branch for releases.

**Comment by atilatosta** [comment]
@mediumTaj  Yes, that's what I think. And we'll follow your suggestion to create the branches from development to issues. Right?

**Comment by mediumTaj** [comment]
Yes, don't work directly off `development`. The `development` and `master` will be protected branches and we will only be able to merge via pull request and review. Create feature branches from issues and if there is not an issue, please create one so we can track what's going on.

I just pulled down the latest development - looks good! I am getting a fail in stt integration test - Recognize_Sucess and DeleteSession_Success. Any ideas why? I'm looking into it too.

**Comment by atilatosta** [comment]
@mediumTaj What is the error message? Recognize should be why I did not upload the .wav file:

FileStream audio =
                File.OpenRead("let_it_be.wav");

**Comment by mediumTaj** [comment]
@atilatosta no error, just results count is zero - so the assert fails.

**Comment by maykonsIBM** [comment]
btw @mediumTaj , did the issue `[conversation] Unit test failing` still occur in branch `development` ? I just tested and I did not have any errors.

The error I had in the integrated test. I believe we can close this issue and work on integrated test.

**Comment by mediumTaj** [comment]
@maykonsIBM Agreed.... thank you!!!
