### ISSUE TITLE
[dotnet-standard-sdk] Inconsistency between Model namespaces

### ISSUE THREAD

**Issue by mediumTaj** [atilatosta/dotnet-standard-sdk#38]
There is an inconsistency between `Model` vs `Models` in the namespace of the DataModels.

> IBM.WatsonDeveloperCloud.TextToSpeech.v1.Model

> IBM.WatsonDeveloperCloud.SpeechToText.v1.Models

Which one should we stick with? Or should we have a separate namespace for Data Models? Should we keep Data Models in the version namespace for each service?

**Comment by atilatosta** [comment]
@mediumTaj In fact the Models is the namespace, the Model is the business class. Actually, when I built it, I realized it got a bit confusing. What do you think about this? How are you in the Java SDK?

**Comment by mediumTaj** [comment]
@atilatosta Looks like they use `model`.

https://github.com/watson-developer-cloud/java-sdk/blob/master/discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/Discovery.java

>import com.ibm.watson.developer_cloud.discovery.v1.model.collection.CreateCollectionResponse;
