### ISSUE TITLE
[documentation] Conversation example

### ISSUE THREAD

**Issue by mediumTaj** [atilatosta/dotnet-standard-sdk#43]
Create an example for Conversation service and add code sample to readme.

**Comment by mediumTaj** [comment]
@atilatosta Do you know if the Conversation service is working? I can't get my example to work.

[example](https://github.com/atilatosta/dotnet-standard-sdk/blob/gh-43-conversationSample/examples/IBM.WatsonDeveloperCloud.Conversation.Example/ConversationServiceExample.cs#L41-L59)

on branch `gh-43-conversationSample`

I get an error 
>"Unexpected character encountered while parsing value: {. Path 'context.system.dialog_stack', line 1, position 433."

**Comment by atilatosta** [comment]
@mediumTaj Yes, it was working! Must be deserialization error. I'll check.
