### ISSUE TITLE
[release] Versioning

### ISSUE THREAD

**Issue by mediumTaj** [atilatosta/dotnet-standard-sdk#51]
@atilatosta @maykonsIBM 

How do you guys think we should approach versioning?

I think we should start this alpha release at `v0.1.0-alpha` and iterate until we have all [requirements](https://github.com/atilatosta/dotnet-standard-sdk/issues/2) fulfilled. We will then move to our first release of `v1.0.0` and have bi-weekely releases (dictated by Developer Experience sprints - I can set up milestones) iterating minor version. Major version will iterate when we have introduced a breaking change.

What do you think?

**Comment by atilatosta** [comment]
@mediumTaj Ok. That sounds good to me.
