### ISSUE TITLE
[dotnet-standard-sdk] Automatic documentation generation

### ISSUE THREAD

**Issue by mediumTaj** [atilatosta/dotnet-standard-sdk#6]
Generate documentation via doxygen using inline documentation. Documentation should be generated upon successful integration tests, unit tests and builds on merge to Master for release. This should generate another commit in github with updated documentation which will be the release.

**Comment by mediumTaj** [comment]
We should be using `GitHub Pages` for documentation. @atilatosta Is there any way I can get access to the repo settings? Can you go into the repo settings and enable GitHub Pages for the `gh-6-documentationGeneration` and if you can `develop`?

**Comment by atilatosta** [comment]
@mediumTaj The repo settings only have this options:

master branch
master branch/docs folder
none (this is what is marked now)

**Comment by mediumTaj** [comment]
@atilatosta can you check if gh-pages branch showed up?

**Comment by mediumTaj** [comment]
Added Doxyfile and code to generate documentation into AppVeyor

```
nuget install -Verbosity quiet -OutputDirectory packages -Version 1.8.13 Doxygen
```

```
.\packages\Doxygen.1.8.13\tools\doxygen.exe Doxyfile
```

Builds are failing right now. Because undocumented methods? We need to now push this directory to `gh-pages` branch and connect GithubPages to the proper documentation.

**Comment by atilatosta** [comment]
@mediumTaj Yes. Now, i can see the gh-pages in the repo settings. I will see the error.

**Comment by mediumTaj** [comment]
Building documentation and pushing to `gh-pages` docs directory under current branch name
```
.\packages\Doxygen.1.8.13\tools\doxygen.exe Doxyfile
git config --global user.email "wps@us.ibm.com"
git config --global user.name "Watson Github Bot"
git clone --quiet --branch=gh-pages https://$env:GH_TOKEN@github.com/atilatosta/dotnet-standard-sdk.git gh-pages
if(Test-Path -Path gh-pages\docs\$env:APPVEYOR_REPO_BRANCH)
{
  rm gh-pages\docs\$env:APPVEYOR_REPO_BRANCH -r -force
}
mkdir -p gh-pages\docs\$env:APPVEYOR_REPO_BRANCH
mv .\docs\html gh-pages\docs\$env:APPVEYOR_REPO_BRANCH
cd gh-pages
git add -A
git commit -m "Updated documentation for $env:APPVEYOR_REPO_BRANCH"
git push origin gh-pages
cd ../
```

Need to create an index page for this branch, and add links to appropriate documentation. Also need a link to latest release whenever a release is tagged.

**Comment by mediumTaj** [comment]
Documentation and index page is being generated.

https://atilatosta.github.io/dotnet-standard-sdk/
