### ISSUE TITLE
[dotnet-standard-sdk] Continuous Integration

### ISSUE THREAD

**Issue by mediumTaj** [atilatosta/dotnet-standard-sdk#8]
Investigate `Travis` vs `AppVeyor` and integrate into the SDK. Can we do everything with `AppVeyor`? Is this better?

**Comment by mediumTaj** [comment]
@atilatosta can you add me to your AppVeyor for the dotnet-standard-sdk? I realize that I signed up and its given me a separate appveyor for the same repo.  Also do you have any idea where this error might be coming from?

https://ci.appveyor.com/project/mediumTaj/dotnet-standard-sdk

```
Command executed with exception: C:\projects\dotnet-standard-sdk\src\IBM.WatsonDeveloperCloud.PersonalityInsights\v3\Models\ProfileOptions.cs(93,20): warning CS0414: The field 'ProfileOptions.ProfileOptionsBuilder._contentLanguage' is assigned but its value is never used
```

I cloned from your development branch and I don't think I've made any changes but it does not appear on your appveyor log. _contentLanguage is used.

**Comment by mediumTaj** [comment]
It's looking like we cannot calculate code coverage using OpenCover with Travis. I get the following error from OpenCover:

```
log4net:ERROR Could not create Appender [ColoredConsoleAppender] of type [log4net.Appender.ColoredConsoleAppender]. Reported error follows.
System.EntryPointNotFoundException: GetConsoleOutputCP
  at (wrapper managed-to-native) log4net.Appender.ColoredConsoleAppender:GetConsoleOutputCP ()
  at log4net.Appender.ColoredConsoleAppender.ActivateOptions () [0x00035] in <dc05a9e165e94f46b41075fe5d8bfb59>:0 
  at log4net.Repository.Hierarchy.XmlHierarchyConfigurator.ParseAppender (System.Xml.XmlElement appenderElement) [0x001f8] in <dc05a9e165e94f46b41075fe5d8bfb59>:0 
log4net:ERROR Appender named [ColoredConsoleAppender] not found.
```

Apparently ColoredConsoleAppender is windows only. https://github.com/OpenCover/opencover/issues/220

**Comment by atilatosta** [comment]
@mediumTaj what is your e-mail on AppVeyor?

**Comment by atilatosta** [comment]
@mediumTaj send me by e-mail!

**Comment by mediumTaj** [comment]
One more thing @atilatosta can you go into your travis and disable travis build of the dotnet-standard-sdk? Just so we stop getting emails that the build fails.

**Comment by mediumTaj** [comment]
Removed old after-test script below

```
**\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:dotnet.exe -targetargs:" test --no-build C:\projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.LanguageTranslator.UnitTests -noshadow /appveyor" -filter:"+[IBM.WatsonDeveloperCloud.LanguageTranslator*]* -[IBM.WatsonDeveloperCloud.LanguageTranslator.UnitTests*]*" -skipautoprops -output:.\coverage-results\results.xml
```

**Comment by mediumTaj** [comment]
I have a successful AppVeyor build.

**Comment by atilatosta** [comment]
@mediumTaj very good! I was not able to integrate with Coveralls.io.

**Comment by atilatosta** [comment]
@mediumTaj I removed the repository from Travis

**Comment by mediumTaj** [comment]
Thanks Atila!

I'm seeing an issue where AppVeyor is not finding all of the tests. The log says it found 26 tests but Visual Studio Test Explorer lists 52 tests. Is there anything I'm missing here? I changed AppVeyor test settings to include

```
**\*.UnitTests.dll
**\*.IntegrationTests.dll
```

Also, I'm not sure OpenCover is finding all of the tests either.

I'll keep taking a look on Monday. Have a good weekend!

**Comment by atilatosta** [comment]
@mediumTaj because in the after tests script was only to run the LanguageTranslator coverage. I have not yet been able to make the filter identify all, without having to add one by one.

rm -rf coverage
mkdir coverage
"C:\projects\dotnet-standard-sdk\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe" "-target:C:\Program Files\dotnet\dotnet.exe" -targetargs:"test -f netcoreapp1.0 -c release test\IBM.WatsonDeveloperCloud.LanguageTranslator.UnitTests" -mergeoutput -hideskipped:File "-output:coverage\coverage.xml" -oldStyle -filter:"+[IBM.WatsonDeveloperCloud.LanguageTranslator*]* -[IBM.WatsonDeveloperCloud.LanguageTranslator.*Tests*]*" "-searchdirs:$testdir\bin\release\netcoreapp1.0" -register:user
"C:\projects\dotnet-standard-sdk\packages\ReportGenerator.2.4.5.0\tools\ReportGenerator.exe" "-reports:coverage\coverage.xml" -targetdir:coverage -verbosity:Error
"C:\projects\dotnet-standard-sdk\packages\coveralls.net.0.7.0\tools\csmacnz.Coveralls.exe" --opencover -i "coverage\coverage.xml" --useRelativePaths

**Comment by mediumTaj** [comment]
Yeah, I was trying to get them to find all of the tests this weekend as well. I do see this warning when Appveyor (not opencover) is trying to discover tests. 

```
Warning: No test is available in 
C:\projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.Conversation.IntegrationTests\bin\Release\netcoreapp1.0\IBM.WatsonDeveloperCloud.Conversation.IntegrationTests.dll 
C:\projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.Conversation.UnitTests\bin\Release\netcoreapp1.0\IBM.WatsonDeveloperCloud.Conversation.UnitTests.dll 
C:\projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.LanguageTranslator.IntegrationTests\bin\Release\netcoreapp1.0\IBM.WatsonDeveloperCloud.LanguageTranslator.IntegrationTests.dll 
C:\projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.LanguageTranslator.UnitTests\bin\Release\netcoreapp1.0\IBM.WatsonDeveloperCloud.LanguageTranslator.UnitTests.dll 
C:\projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.SpeechToText.UnitTests\bin\Release\netcoreapp1.0\IBM.WatsonDeveloperCloud.SpeechToText.UnitTests.dll 
C:\projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.ToneAnalyzer.IntegrationTests\bin\Release\netcoreapp1.0\IBM.WatsonDeveloperCloud.ToneAnalyzer.IntegrationTests.dll 
C:\projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.ToneAnalyzer.UnitTests\bin\Release\netcoreapp1.0\IBM.WatsonDeveloperCloud.ToneAnalyzer.UnitTests.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
```

It also looks like it only runs 26 tests where VisualStudio can find 50+ tests

```
Executing Tests ... 
Passed   Constructor_HttpClient_Null
Passed   Constructor_UserName_Null
Passed   Constructor_PassWord_Null
Passed   Constructor_With_UserName_Password
Passed   ListModels_Success
Passed   ListModels_Catch_Exception
Passed   CreateModel_Success
Passed   CreateModel_BaseModelId_Null
Passed   CreateModel_ModelName_WithSpaces
Passed   CreateModel_File_Null
Passed   CreateModel_Catch_Exception
Passed   DeleteModel_Success
Passed   DeleteModel_ModelId_Null
Passed   DeleteModel_Catch_Exception
Passed   GetModelDetails_Success
Passed   GetModelDetails_ModelId_Null
Passed   GetModelDetails_Catch_Exception
Passed   Translate_Success_WithModel
Passed   Translate_Success_With_Source_Target
Passed   Translate_Success_WithModel_List
Passed   Translate_Success_With_Source_Target_List
Passed   Translate_Catch_Exception
Passed   GetIdentifiableLanguages_Success
Passed   GetIdentifiableLanguages_Catch_Exception
Passed   Identify_Success
Passed   Identify_Catch_Exception
============ Test Run Summary ============
Total tests: 26. Passed: 26. Failed: 0. Skipped: 0
Test Run Successful.
```

I tried to add the rest of the tests in the targetargs in the opencover call but opencover couldnt understand

```
"C:\projects\dotnet-standard-sdk\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe" "-target:C:\Program Files\dotnet\dotnet.exe" "-targetargs:test -f netcoreapp1.0 -c release C:\projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.LanguageTranslator.UnitTests C:\projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.LanguageTranslator.IntegrationTests C:\projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.Conversation.UnitTests C:\projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.Conversation.IntegrationTests C:\projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.Discovery.UnitTests C:\projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.Discovery.IntegrationTests C:\projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.PersonalityInsights.UnitTests C:\projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.PersonalityInsights.IntegrationTests C:\projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.SpeechToText.UnitTests C:\projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.SpeechToText.IntegrationTests C:\projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.TextToSpeech.UnitTests C:\projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.TextToSpeech.IntegrationTests C:\projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.ToneAnalyzer.UnitTests C:\projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.ToneAnalyzer.IntegrationTests C:\projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.VisualRecognition.UnitTests C:\projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.VisualRecognition.IntegrationTests /noshadow" -mergeoutput -hideskipped:File "-output:coverage\coverage.xml" -oldStyle -filter:"+[IBM.WatsonDeveloperCloud.*]* -[IBM.WatsonDeveloperCloud.*.*Tests*]*" "-searchdirs:$testdir\bin\release\netcoreapp1.0" -register:user

```

**Comment by atilatosta** [comment]
@mediumTaj I saw this comment, may be a possible solution:
https://github.com/dotnet/cli/issues/3136?#issuecomment-272648964

**Comment by mediumTaj** [comment]
@atilatosta I wrote a test script from what they have in that comment. I think it looks good. We are failing a few integration tests but I think we are finding all of them. Can you take a look at the log and confirm? 

https://ci.appveyor.com/project/atilatosta/dotnet-standard-sdk/build/1.0.55

I'm still looking into the other errors. Do I need to adjust the project.json of each service, integration and unit test?

Also, it seems to be running the tests twice. Once when I call `dotnet test` and once in the OpenCover call. Is this normal? Should we omit the inital `dotnet test`?

**Comment by mediumTaj** [comment]
This is looking pretty good - Creating pull request for review.

**Comment by atilatosta** [comment]
@mediumTaj Very good!
